on:
  workflow_call:
    outputs:
      config:
        description: "The runner's configuration"
        value: ${{ jobs.runner.outputs.config }}

jobs:
  runner:
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.config.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: config
        with:
          script: |
            if (`${context.repo.owner}/${context.repo.repo}` === 'ipfs/kubo') {
              return {
                labels: ['self-hosted', 'linux', 'x64', 'kubo'],
                parallel: 10
              }
            } else {
              return {
                labels: ['ubuntu-latest'],
                parallel: 3
              }
            }
      - run: echo ${{ steps.config.outputs.result }}
