---
name: Testground PR Checker

on:
  workflow_dispatch:
  push:


jobs:
  testground:
    if: github.repository == 'ipfs/go-ipfs' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: ${{ matrix.composition_file }}
    strategy:
      matrix:
        include:
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/bitswap
            composition_file: testplans/bitswap/_compositions/small-k8s.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/bitswap
            composition_file: testplans/bitswap/_compositions/medium-k8s.toml
          - backend_addr: ci.testground.ipfs.team
            backend_proto: https
            plan_directory: testplans/bitswap
            composition_file: testplans/bitswap/_compositions/large-k8s.toml
    steps:
      - uses: actions/checkout@v2
      - name: testground run
        uses: testground/testground-github-action@v1
        timeout-minutes: 5
        with:
          backend_addr: ${{ matrix.backend_addr }}
          backend_proto: ${{ matrix.backend_proto }}
          plan_directory: ${{ matrix.plan_directory }}
          composition_file: ${{ matrix.composition_file }}
